language: node_js
node_js: node
cache:
  directories:
    - node_modules
script:
  - npm test
env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s c2b20aac-a624-4cf2-a662-796196954f27 -t 9926026ecd8ef6611987f5ed077ca127180ee1d85a8f53703cbe71315fd4a34a -p ./build
  skip_cleanup: true
  on:
    branch: master
